load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "rust_icu_unum",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "renaming",
        "static",
        "icu_version_in_env",
    ],
    edition = "2021",
    proc_macro_deps = [
        "@crates//:paste",
    ],
    rustc_env = {
        "RUST_ICU_MAJOR_VERSION_NUMBER": "74",
    },
    visibility = ["//visibility:public"],
    deps = [
        "//rust_icu_common",
        "//rust_icu_sys",
        "//rust_icu_uformattable",
        "//rust_icu_uloc",
        "//rust_icu_ustring",
        "@crates//:anyhow",
        "@crates//:log",
    ],
)

rust_test(
    name = "rust_icu_unum_test",
    crate = ":rust_icu_unum",
    crate_features = [
        "renaming",
        "static",
        "icu_version_in_env",
    ],
    rustc_env = {
        "RUST_ICU_MAJOR_VERSION_NUMBER": "74",
    },
    deps = ["@crates//:anyhow"],
)

load("//bazel:publish.bzl", "cargo_publish")

cargo_publish(
    name = "publish",
    crate_dir = "rust_icu_unum",
    visibility = ["//visibility:public"],
    deps = [
        "//rust_icu_common:publish",
        "//rust_icu_sys:publish",
        "//rust_icu_uformattable:publish",
        "//rust_icu_uloc:publish",
        "//rust_icu_ustring:publish",
    ],
)
