load("//bazel:publish.bzl", "cargo_publish")

cargo_publish(
    name = "publish_all",
    deps = [
        "//ecma402_traits:publish",
        "//rust_icu:publish",
        "//rust_icu_common:publish",
        "//rust_icu_ecma402:publish",
        "//rust_icu_intl:publish",
        "//rust_icu_release:publish",
        "//rust_icu_sys:publish",
        "//rust_icu_ubrk:publish",
        "//rust_icu_ucal:publish",
        "//rust_icu_uchar:publish",
        "//rust_icu_ucnv:publish",
        "//rust_icu_ucol:publish",
        "//rust_icu_ucsdet:publish",
        "//rust_icu_udat:publish",
        "//rust_icu_udata:publish",
        "//rust_icu_uenum:publish",
        "//rust_icu_uformattable:publish",
        "//rust_icu_ulistformatter:publish",
        "//rust_icu_uloc:publish",
        "//rust_icu_umsg:publish",
        "//rust_icu_unorm2:publish",
        "//rust_icu_unum:publish",
        "//rust_icu_unumberformatter:publish",
        "//rust_icu_upluralrules:publish",
        "//rust_icu_ures:publish",
        "//rust_icu_ustring:publish",
        "//rust_icu_utext:publish",
        "//rust_icu_utrans:publish",
    ],
)

label_flag(
    name = "icu_backend",
    build_setting_default = "@icu_74//:icu",
    visibility = ["//visibility:public"],
)
