load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "rust_icu_uchar",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    crate_features = ["renaming", "static", "icu_version_in_env"],
    rustc_env = {
        "RUST_ICU_MAJOR_VERSION_NUMBER": "74",
    },
    deps = [
        "@crates//:log", "//rust_icu_common:rust_icu_common", "//rust_icu_sys:rust_icu_sys"
    ],
    proc_macro_deps = [
        "@crates//:paste"
    ],
    visibility = ["//visibility:public"],
)

rust_test(

    name = "rust_icu_uchar_test",
    crate = ":rust_icu_uchar",
    crate_features = ["renaming", "static", "icu_version_in_env"],
    rustc_env = {
        "RUST_ICU_MAJOR_VERSION_NUMBER": "74",
    },
    deps = [],
)
