name: Auto Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  workflows: write # Not sure if this is necessary

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # If a release was created (PR was merged), we proceed to publish
      - name: Checkout Code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install System Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: sudo apt-get update && sudo apt-get install -y libicu-dev pkg-config llvm llvm-dev clang

      - name: Setup Bazel
        if: ${{ steps.release.outputs.release_created }}
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Bazel Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: bazel run //bazel:publish_all
