name: Bazel Presubmit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - bazel-core-infrastructure
      - bazel-icu-compilation
      - bazel-migration
      - bazel-rust-icu-sys
      - bazel-other-crates
      - bazel-docs
      - bazel-auto-publish

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bazel_version: ["8.7.0", "9.2.0"]
    steps:
      - uses: actions/checkout@v4

      - name: Write Bazel version
        run: echo "${{ matrix.bazel_version }}" > .bazelversion

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Test all targets
        run: |
          set +e
          # We force tests to run serially to avoid global ICU timezone mutation races.
          bazel test --jobs=1 --test_env=RUST_TEST_THREADS=1 //...
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 4 ]; then
            echo "No tests found. Moving on."
            exit 0
          elif [ $EXIT_CODE -ne 0 ]; then
            exit $EXIT_CODE
          fi
