name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "43 17 * * 0"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-default-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Test ICU `main`'
        run: 'make DOCKER_TEST_ENV=rust_icu_testenv-current docker-test-current'

